FROM nginx:1.17.4-perl

RUN apt update -y && \
    apt install inetutils-ping -y && \
    apt install dnsutils  -y && \
    apt install net-tools  -y && \
    apt install iproute2  -y  && \
    apt install curl -y





